FROM node:20-alpine
WORKDIR /src/app

ENV PORT=3000
ENV MONGODB_URI=${MONGODB_URI}
ENV BE_URL=${BE_URL}
ENV FE_URL=${FE_URL}
ENV IMAGE_BB_API_KEY=${IMAGE_BB_API_KEY}
ENV REST_API_KEY=${REST_API_KEY}
ENV KAKAO_APP_KEY=${KAKAO_APP_KEY}
ENV CLIENT_SECRET=${CLIENT_SECRET}
ENV SECRET_KEY=${SECRET_KEY}

COPY package*.json ./
RUN npm install
COPY . .
CMD [ "npm", "run", "dev" ]
EXPOSE 8080
