FROM node:20-alpine
WORKDIR /src/app

ARG PORT
ARG MONGODB_URI
ARG BE_URL
ARG FE_URL
ARG IMAGE_BB_API_KEY
ARG REST_API_KEY
ARG KAKAO_APP_KEY
ARG CLIENT_SECRET
ARG SECRET_KEY
ARG FE_URL_DEV
ARG FE_URL_LOCAL

ENV PORT=${PORT}
ENV MONGODB_URI=${MONGODB_URI}
ENV BE_URL=${BE_URL}
ENV FE_URL=${FE_URL}
ENV IMAGE_BB_API_KEY=${IMAGE_BB_API_KEY}
ENV REST_API_KEY=${REST_API_KEY}
ENV KAKAO_APP_KEY=${KAKAO_APP_KEY}
ENV CLIENT_SECRET=${CLIENT_SECRET}
ENV SECRET_KEY=${SECRET_KEY}
ENV FE_URL_DEV=${FE_URL_DEV}
ENV FE_URL_LOCAL=${FE_URL_LOCAL}

COPY package*.json ./
RUN npm install
COPY . .
CMD [ "npm", "run", "dev" ]
EXPOSE 443
